// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTCJ2Wa-XBJDgk_oKoEO5WZ5bIroiro4',
    appId: '1:574124394505:web:9c50bf994295b50b1710d8',
    messagingSenderId: '574124394505',
    projectId: 'tinyml-washingmachine',
    authDomain: 'tinyml-washingmachine.firebaseapp.com',
    databaseURL: 'https://tinyml-washingmachine-default-rtdb.firebaseio.com',
    storageBucket: 'tinyml-washingmachine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUkMj7Mq1z_oXosHgHjRzAGSayU8MA-o',
    appId: '1:574124394505:android:bc5ef88238c8114f1710d8',
    messagingSenderId: '574124394505',
    projectId: 'tinyml-washingmachine',
    databaseURL: 'https://tinyml-washingmachine-default-rtdb.firebaseio.com',
    storageBucket: 'tinyml-washingmachine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUadPfzvf87jcozOaP57Vm1ORZwdEyjgc',
    appId: '1:574124394505:ios:3df9b1fa163cc5b51710d8',
    messagingSenderId: '574124394505',
    projectId: 'tinyml-washingmachine',
    databaseURL: 'https://tinyml-washingmachine-default-rtdb.firebaseio.com',
    storageBucket: 'tinyml-washingmachine.firebasestorage.app',
    iosBundleId: 'com.example.tinymlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUadPfzvf87jcozOaP57Vm1ORZwdEyjgc',
    appId: '1:574124394505:ios:3df9b1fa163cc5b51710d8',
    messagingSenderId: '574124394505',
    projectId: 'tinyml-washingmachine',
    databaseURL: 'https://tinyml-washingmachine-default-rtdb.firebaseio.com',
    storageBucket: 'tinyml-washingmachine.firebasestorage.app',
    iosBundleId: 'com.example.tinymlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaTCJ2Wa-XBJDgk_oKoEO5WZ5bIroiro4',
    appId: '1:574124394505:web:907a13550468653f1710d8',
    messagingSenderId: '574124394505',
    projectId: 'tinyml-washingmachine',
    authDomain: 'tinyml-washingmachine.firebaseapp.com',
    databaseURL: 'https://tinyml-washingmachine-default-rtdb.firebaseio.com',
    storageBucket: 'tinyml-washingmachine.firebasestorage.app',
  );
}
