"""Generate local firmware and Flutter config files from .env.

The script writes:
  - firmware_v11/env_config.h
  - tinyml_app/lib/app_config.dart

Both generated files are ignored by Git because they may contain credentials.
"""

from __future__ import annotations

import argparse
from pathlib import Path


REQUIRED_KEYS = (
    "WIFI_SSID",
    "WIFI_PASSWORD",
    "MQTT_HOST",
    "MQTT_PORT",
    "MQTT_USERNAME",
    "MQTT_PASSWORD",
    "MQTT_TOPIC",
)


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip().lstrip("\ufeff")
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def dart_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def require_values(values: dict[str, str]) -> None:
    missing = [key for key in REQUIRED_KEYS if not values.get(key)]
    if missing:
        raise SystemExit("Missing values in .env: " + ", ".join(missing))
    try:
        int(values["MQTT_PORT"])
    except ValueError as exc:
        raise SystemExit("MQTT_PORT must be an integer") from exc


def write_firmware_config(values: dict[str, str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by tools/generate_env_config.py. Do not commit.",
                f'const char* WIFI_SSID = "{c_string(values["WIFI_SSID"])}";',
                f'const char* WIFI_PASSWORD = "{c_string(values["WIFI_PASSWORD"])}";',
                f'const char* MQTT_HOST = "{c_string(values["MQTT_HOST"])}";',
                f'const int MQTT_PORT = {int(values["MQTT_PORT"])};',
                f'const char* MQTT_USER = "{c_string(values["MQTT_USERNAME"])}";',
                f'const char* MQTT_PASSWORD = "{c_string(values["MQTT_PASSWORD"])}";',
                f'const char* MQTT_TOPIC = "{c_string(values["MQTT_TOPIC"])}";',
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_flutter_config(values: dict[str, str], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "// Generated by tools/generate_env_config.py. Do not commit.",
                "class AppConfig {",
                f"  static const broker = '{dart_string(values['MQTT_HOST'])}';",
                f"  static const topic = '{dart_string(values['MQTT_TOPIC'])}';",
                f"  static const port = {int(values['MQTT_PORT'])};",
                f"  static const username = '{dart_string(values['MQTT_USERNAME'])}';",
                f"  static const password = '{dart_string(values['MQTT_PASSWORD'])}';",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate local config files from .env"
    )
    parser.add_argument("--env", default=".env")
    parser.add_argument("--firmware-out", default="firmware_v11/env_config.h")
    parser.add_argument("--flutter-out", default="tinyml_app/lib/app_config.dart")
    args = parser.parse_args()

    env_path = Path(args.env)
    if not env_path.exists():
        raise SystemExit(f"Missing {env_path}. Copy .env.example to .env first.")

    values = parse_env(env_path)
    require_values(values)
    write_firmware_config(values, Path(args.firmware_out))
    write_flutter_config(values, Path(args.flutter_out))
    print(f"Wrote {args.firmware_out}")
    print(f"Wrote {args.flutter_out}")


if __name__ == "__main__":
    main()
